In [1]:
from utils import pr , measure_time
import numpy as np

In [2]:
N = np.array([1,2,3])
M = np.array([
    [1,2,3],
    [4,5,6]
])
pr(N,'N')
pr(N.shape,'N.shape')
pr(M,'M')
pr(M.shape,'M.shape')


+++++++++++++++++ N ++++++++++++++++++
<class 'numpy.ndarray'>
[1 2 3]
-----

+++++++++++++++++ N.shape ++++++++++++++++++
<class 'tuple'>
(3,)
-----

+++++++++++++++++ M ++++++++++++++++++
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
-----

+++++++++++++++++ M.shape ++++++++++++++++++
<class 'tuple'>
(2, 3)
-----



(2, 3)