In [1]:
from utils import pr , measure_time
import numpy as np

In [2]:
a = pr(np.array([1,2,3]) , 'a')
b = pr(np.array([4,5,6]) , 'b')
pr(a+b , 'a+b')
pr(a-b , 'a-b')

+++++++++++++++++ a ++++++++++++++++++
<class 'numpy.ndarray'>
[1 2 3]
-----

+++++++++++++++++ b ++++++++++++++++++
<class 'numpy.ndarray'>
[4 5 6]
-----

+++++++++++++++++ a+b ++++++++++++++++++
<class 'numpy.ndarray'>
[5 7 9]
-----

+++++++++++++++++ a-b ++++++++++++++++++
<class 'numpy.ndarray'>
[-3 -3 -3]
-----



array([-3, -3, -3])