In [1]:
from utils import pr , measure_time
import numpy as np

In [2]:
v = np.array([2.0, -1.0, 3.5])
pr(v, 'v')
pr(v.shape, 'v.shape')

+++++++++++++++++ v ++++++++++++++++++
<class 'numpy.ndarray'>


array([ 2. , -1. ,  3.5])

-----

+++++++++++++++++ v.shape ++++++++++++++++++
<class 'tuple'>


(3,)

-----



In [3]:
u = np.array([1.0, 0.0, -1.0])
pr(v , 'v')
pr(u , 'u')
pr(v+u , 'v+u')

+++++++++++++++++ v ++++++++++++++++++
<class 'numpy.ndarray'>


array([ 2. , -1. ,  3.5])

-----

+++++++++++++++++ u ++++++++++++++++++
<class 'numpy.ndarray'>


array([ 1.,  0., -1.])

-----

+++++++++++++++++ v+u ++++++++++++++++++
<class 'numpy.ndarray'>


array([ 3. , -1. ,  2.5])

-----

