In [1]:
from utils import pr 
import numpy as np

In [4]:
x = np.linspace(0,10,20)
y = 2 * x
pr(x)
pr(y)
z = np.column_stack((x , y))
pr(z)

+++++++++++++++++++++++++++++++++++
<class 'numpy.ndarray'>


array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

-----

+++++++++++++++++++++++++++++++++++
<class 'numpy.ndarray'>


array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

-----

+++++++++++++++++++++++++++++++++++
<class 'numpy.ndarray'>


array([[ 0.        ,  0.        ],
       [ 0.52631579,  1.05263158],
       [ 1.05263158,  2.10526316],
       [ 1.57894737,  3.15789474],
       [ 2.10526316,  4.21052632],
       [ 2.63157895,  5.26315789],
       [ 3.15789474,  6.31578947],
       [ 3.68421053,  7.36842105],
       [ 4.21052632,  8.42105263],
       [ 4.73684211,  9.47368421],
       [ 5.26315789, 10.52631579],
       [ 5.78947368, 11.57894737],
       [ 6.31578947, 12.63157895],
       [ 6.84210526, 13.68421053],
       [ 7.36842105, 14.73684211],
       [ 7.89473684, 15.78947368],
       [ 8.42105263, 16.84210526],
       [ 8.94736842, 17.89473684],
       [ 9.47368421, 18.94736842],
       [10.        , 20.        ]])

-----

