In [1]:
from utils import pr , measure_time
import numpy as np
import pandas as pd

In [3]:
v = np.array([3,5])
B = np.array([[1,-1],
              [1,1]])
c = np.linalg.solve(B,v)
pr(c)
pr(B@c)

+++++++++++++++++++++++++++++++++++
<class 'numpy.ndarray'>


array([4., 1.])

-----

+++++++++++++++++++++++++++++++++++
<class 'numpy.ndarray'>


array([3., 5.])

-----



In [6]:
def T(v):
    x , y = v
    return np.array([2*x + y,
                     x - y])
e1 = np.array([1,0])
e2 = np.array([0,1])
pr((T(e1) , T(e2)))
A = np.array([[2,1],
             [1,-1]])
x = np.array([3,5])
pr(T(x))
pr(A@x)

+++++++++++++++++++++++++++++++++++
<class 'tuple'>


(array([2, 1]), array([ 1, -1]))

-----

+++++++++++++++++++++++++++++++++++
<class 'numpy.ndarray'>


array([11, -2])

-----

+++++++++++++++++++++++++++++++++++
<class 'numpy.ndarray'>


array([11, -2])

-----



In [7]:
A = np.array([
    [2,0],
    [0,1]
])
B = np.array([
    [0,-1],
    [1,0]
])
v = np.array([1,2])
step1 = A @ v
step2 = B @ step1
pr(step2)
combined_transformation = B @ A
pr(combined_transformation @ v)

+++++++++++++++++++++++++++++++++++
<class 'numpy.ndarray'>


array([-2,  2])

-----

+++++++++++++++++++++++++++++++++++
<class 'numpy.ndarray'>


array([-2,  2])

-----



In [9]:
A = np.array([
    [1,2],
    [2,4]
])
pr(np.linalg.matrix_rank(A))
x = np.array([5,7])
y = np.array([3,15])
pr(A@x)
pr(A@y)

+++++++++++++++++++++++++++++++++++
<class 'numpy.int64'>


np.int64(1)

-----

+++++++++++++++++++++++++++++++++++
<class 'numpy.ndarray'>


array([19, 38])

-----

+++++++++++++++++++++++++++++++++++
<class 'numpy.ndarray'>


array([33, 66])

-----

