In [1]:
from utils import pr
import numpy as np
import matplotlib.pyplot as plt
import torch
import tensorflow as tf

In [3]:
x = np.array([25, 2, 5] , dtype=np.float16)
pr(x , 'x')
pr(len(x) , 'len(x)')
pr(x.shape , 'x.shape')
pr(type(x) , 'type(x)')
pr(x[0] , 'x[0]')
pr(type(x[0]) , 'type(x[0])')

+++++++++++++++++ x ++++++++++++++++++
<class 'numpy.ndarray'>


array([25.,  2.,  5.], dtype=float16)

-----

+++++++++++++++++ len(x) ++++++++++++++++++
<class 'int'>


3

-----

+++++++++++++++++ x.shape ++++++++++++++++++
<class 'tuple'>


(3,)

-----

+++++++++++++++++ type(x) ++++++++++++++++++
<class 'type'>


numpy.ndarray

-----

+++++++++++++++++ x[0] ++++++++++++++++++
<class 'numpy.float16'>


np.float16(25.0)

-----

+++++++++++++++++ type(x[0]) ++++++++++++++++++
<class 'type'>


numpy.float16

-----



In [5]:
pr(x , 'x')
pr(x.shape , 'x.shape')
pr(x.T , 'x.T')
pr(x.T.shape , 'x.T.shape')

+++++++++++++++++ x ++++++++++++++++++
<class 'numpy.ndarray'>


array([25.,  2.,  5.], dtype=float16)

-----

+++++++++++++++++ x.shape ++++++++++++++++++
<class 'tuple'>


(3,)

-----

+++++++++++++++++ x.T ++++++++++++++++++
<class 'numpy.ndarray'>


array([25.,  2.,  5.], dtype=float16)

-----

+++++++++++++++++ x.T.shape ++++++++++++++++++
<class 'tuple'>


(3,)

-----



In [6]:
x = np.array([[25, 2, 5]] , dtype=np.float16)
pr(x , 'x')
pr(x.shape , 'x.shape')
pr(x.T , 'x.T')
pr(x.T.shape , 'x.T.shape')

+++++++++++++++++ x ++++++++++++++++++
<class 'numpy.ndarray'>


array([[25.,  2.,  5.]], dtype=float16)

-----

+++++++++++++++++ x.shape ++++++++++++++++++
<class 'tuple'>


(1, 3)

-----

+++++++++++++++++ x.T ++++++++++++++++++
<class 'numpy.ndarray'>


array([[25.],
       [ 2.],
       [ 5.]], dtype=float16)

-----

+++++++++++++++++ x.T.shape ++++++++++++++++++
<class 'tuple'>


(3, 1)

-----



In [7]:
x = torch.tensor([25,2,5])
pr(x , 'torch tensor')
x = tf.Variable([25,2,5])
pr(x , 'TensorFlow tensor')

+++++++++++++++++ torch tensor ++++++++++++++++++
<class 'torch.Tensor'>


tensor([25,  2,  5])

-----

+++++++++++++++++ TensorFlow tensor ++++++++++++++++++
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

-----

