In [1]:
from utils import pr
import numpy as np
import matplotlib.pyplot as plt
import torch
import tensorflow as tf

In [2]:
x = np.array([25,2,5])
norm = np.linalg.norm(x)
pr(norm , 'norm')

+++++++++++++++++ norm ++++++++++++++++++
<class 'numpy.float64'>


np.float64(25.573423705088842)

-----



In [3]:
i = np.array([1,0])
j = np.array([0,1])
pr(np.dot(i , j))

+++++++++++++++++++++++++++++++++++
<class 'numpy.int64'>


np.int64(0)

-----



In [9]:
X = np.array([[25, 2], 
              [5, 26], 
              [3, 7]])
pr( X.shape, 'X.shape')
pr( X.size, 'X.size')
pr( X[:,0], 'X[:,0]')
pr( X[1,:], 'X[1,:]')
pr( X[0:2,0:2], 'X[0:2,0:2]')

+++++++++++++++++ X.shape ++++++++++++++++++
<class 'tuple'>


(3, 2)

-----

+++++++++++++++++ X.size ++++++++++++++++++
<class 'int'>


6

-----

+++++++++++++++++ X[:,0] ++++++++++++++++++
<class 'numpy.ndarray'>


array([25,  5,  3])

-----

+++++++++++++++++ X[1,:] ++++++++++++++++++
<class 'numpy.ndarray'>


array([ 5, 26])

-----

+++++++++++++++++ X[0:2,0:2] ++++++++++++++++++
<class 'numpy.ndarray'>


array([[25,  2],
       [ 5, 26]])

-----



In [10]:
X = torch.tensor([[25, 2], 
              [5, 26], 
              [3, 7]])
pr( X.shape, 'X.shape')
pr( X.size, 'X.size')
pr( X[:,0], 'X[:,0]')
pr( X[1,:], 'X[1,:]')
pr( X[0:2,0:2], 'X[0:2,0:2]')

+++++++++++++++++ X.shape ++++++++++++++++++
<class 'torch.Size'>


torch.Size([3, 2])

-----

+++++++++++++++++ X.size ++++++++++++++++++
<class 'builtin_function_or_method'>


<function Tensor.size>

-----

+++++++++++++++++ X[:,0] ++++++++++++++++++
<class 'torch.Tensor'>


tensor([25,  5,  3])

-----

+++++++++++++++++ X[1,:] ++++++++++++++++++
<class 'torch.Tensor'>


tensor([ 5, 26])

-----

+++++++++++++++++ X[0:2,0:2] ++++++++++++++++++
<class 'torch.Tensor'>


tensor([[25,  2],
        [ 5, 26]])

-----



In [13]:
X = tf.Variable([[25, 2], 
              [5, 26], 
              [3, 7]])
pr( tf.rank(X), 'tf.rank(X)')
pr( tf.size(X), 'tf.size(X)')
pr( X[:,0], 'X[:,0]')
pr( X[1,:], 'X[1,:]')
pr( X[0:2,0:2], 'X[0:2,0:2]')

+++++++++++++++++ tf.rank(X) ++++++++++++++++++
<class 'tensorflow.python.framework.ops.EagerTensor'>


<tf.Tensor: shape=(), dtype=int32, numpy=2>

-----

+++++++++++++++++ tf.size(X) ++++++++++++++++++
<class 'tensorflow.python.framework.ops.EagerTensor'>


<tf.Tensor: shape=(), dtype=int32, numpy=6>

-----

+++++++++++++++++ X[:,0] ++++++++++++++++++
<class 'tensorflow.python.framework.ops.EagerTensor'>


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25,  5,  3], dtype=int32)>

-----

+++++++++++++++++ X[1,:] ++++++++++++++++++
<class 'tensorflow.python.framework.ops.EagerTensor'>


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26], dtype=int32)>

-----

+++++++++++++++++ X[0:2,0:2] ++++++++++++++++++
<class 'tensorflow.python.framework.ops.EagerTensor'>


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25,  2],
       [ 5, 26]], dtype=int32)>

-----

