In [2]:
from utils import pr
import numpy as np
import matplotlib.pyplot as plt
import torch
import tensorflow as tf

In [7]:
X = np.array(5) 
pr(X , 'numpy scalar')
pr(X.shape , 'numpy scalar shape')
V = np.array([1,2,3])
pr(V , 'numpy vector')
pr(V.shape , 'numpy vector shape')
M = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
pr(M , 'numpy matrix')
pr(M.shape , 'numpy matrix shape')
T = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
pr(T , 'numpy tensor')
pr(T.shape , 'numpy tensor shape')

+++++++++++++++++ numpy scalar ++++++++++++++++++
<class 'numpy.ndarray'>


array(5)

-----

+++++++++++++++++ numpy scalar shape ++++++++++++++++++
<class 'tuple'>


()

-----

+++++++++++++++++ numpy vector ++++++++++++++++++
<class 'numpy.ndarray'>


array([1, 2, 3])

-----

+++++++++++++++++ numpy vector shape ++++++++++++++++++
<class 'tuple'>


(3,)

-----

+++++++++++++++++ numpy matrix ++++++++++++++++++
<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6]])

-----

+++++++++++++++++ numpy matrix shape ++++++++++++++++++
<class 'tuple'>


(2, 3)

-----

+++++++++++++++++ numpy tensor ++++++++++++++++++
<class 'numpy.ndarray'>


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

-----

+++++++++++++++++ numpy tensor shape ++++++++++++++++++
<class 'tuple'>


(2, 2, 2)

-----



In [8]:
x = torch.tensor(25)
pr(x)
pr(x.shape)

+++++++++++++++++++++++++++++++++++
<class 'torch.Tensor'>


tensor(25)

-----

+++++++++++++++++++++++++++++++++++
<class 'torch.Size'>


torch.Size([])

-----



In [10]:
x = tf.Variable(25 , dtype=tf.float32)
pr(x)
pr(x.shape)
pr(x.numpy())

+++++++++++++++++++++++++++++++++++
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=25.0>

-----

+++++++++++++++++++++++++++++++++++
<class 'tensorflow.python.framework.tensor_shape.TensorShape'>


TensorShape([])

-----

+++++++++++++++++++++++++++++++++++
<class 'numpy.float32'>


np.float32(25.0)

-----

